update DGX TF2 tests for 20.02-tf2-py3 NVIDIA TensorFlow image

diff --git a/tests/167_dgx_tf2/submit b/tests/167_dgx_tf2/submit
--- a/tests/167_dgx_tf2/submit
+++ b/tests/167_dgx_tf2/submit
@@ -2,14 +2,17 @@
 
 # Test settings
 BASE=/home/projects/benchmarks/workload
-test=162_dgx_tf2
+test=167_dgx_tf2
 ### nvcr.io/nvidia/tensorflow:20.01-tf2-py3
-failmetric=1750.0
-layers=152
-batch=64
+#failmetric=1750.0
+#layers=152
+#batch=64
+#dataset="resnet"
+### nvcr.io/nvidia/tensorflow:20.02-tf2-py3
+failmetric=4000.0
 dataset="resnet"
 data="/scratch/projects/ai/datasets/imagenet/$dataset"
-i_latest="nvcr.io/nvidia/tensorflow:20.01-tf2-py3"
+i_latest="nvcr.io/nvidia/tensorflow:latest-tf2"
 image=${IMAGE:-$i_latest}
 
 dockerarg="$DOCKERARGV"
@@ -60,11 +63,13 @@ image="$image"
 nscc-docker images
 nscc-docker run $dockerarg \$image < stdin > stdout.\$PBS_JOBID 2> stderr.\$PBS_JOBID
 grep 'Created TensorFlow device .*/device:GPU' stderr.\$PBS_JOBID || { echo job fail ; echo FAIL ; exit 1 ; }
-###nvcr.io/nvidia/tensorflow:20.01-tf2-py3
-grep '^Step: 200 Img/sec' stdout.\$PBS_JOBID > /dev/null  || { echo job fail ; echo FAIL ; exit 1 ; }
+#grep '^Step: 200 Img/sec' stdout.\$PBS_JOBID > /dev/null  || { echo job fail ; echo FAIL ; exit 1 ; }
+grep '^global_step: 200 images_per_sec' stdout.\$PBS_JOBID > /dev/null  || { echo job fail ; echo FAIL ; exit 1 ; }
 failmetric="$failmetric"
-###nvcr.io/nvidia/tensorflow:20.01-tf2-py3
-metric=\`grep '^Step: 190 Img/sec' stdout.\$PBS_JOBID | awk '{print \$NF}'\`
+### nvcr.io/nvidia/tensorflow:20.01-tf2-py3
+#metric=\`grep '^Step: 190 Img/sec' stdout.\$PBS_JOBID | awk '{print \$NF}'\`
+### nvcr.io/nvidia/tensorflow:20.02-tf2-py3
+metric=\`grep '^global_step: 190 images_per_sec' stdout.\$PBS_JOBID | awk '{print \$NF}'\`
 
 echo metric=\"\$metric\"
 echo check performance
@@ -75,22 +80,31 @@ EOF
 
 cat << EOF > stdin
 dataset="$dataset"
-layers="$layers"
-batch="$batch"
+#layers="$layers"
+#batch="$batch"
 data="$data"
 cd /workspace/nvidia-examples/cnn
-### nvcr.io/nvidia/tensorflow:20.01-tf2-py3
+# issue with dataset
+# --data_dir \$data \
+
+### nvcr.io/nvidia/tensorflow:20.02-tf2-py3
 mpiexec --allow-run-as-root -np 8 python \${dataset}.py \
- --layers \$layers \
- -b \$batch \
  -i 200 \
  -u batch \
- --precision=fp16 \
- --data_dir \$data \
- --num_gpus=1 \
- --resnet_version=v1.5 \
- --use_ctl \
- --use_hvd
+ --precision=fp16
+
+### nvcr.io/nvidia/tensorflow:20.01-tf2-py3
+#mpiexec --allow-run-as-root -np 8 python \${dataset}.py \
+# --layers \$layers \
+# -b \$batch \
+# -i 200 \
+# -u batch \
+# --precision=fp16
+# --data_dir \$data \
+# --num_gpus=1 \
+# --resnet_version=v1.5 \
+# --use_ctl \
+# --use_hvd
 EOF
 
 jobid=`qsub $QSUB_ARGS run.pbs`
